config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :show]

  root to: 'books#index'
end

app/models/adapter/google_books.rb
# Adapter::GoogleBooks.new('dogs').fetch_books
# Adapter::Amazon.new('dogs').fetch_books

module Adapter

  class GoogleBooks

    BASE_URL = "https://www.googleapis.com/books/v1/volumes"
    # per the api docs 40 is the max resuls per page
    MAX_RESULTS = 40

    attr_reader :term

    def initialize(term = nil)
      @term = term
    end


    def fetch_books(start_index = 0)
      # make a request to api
      if self.term
        url = "#{BASE_URL}?q=#{self.term}"
      else
        url = "#{BASE_URL}?q=subject:fiction&startIndex=#{start_index}&maxResults=#{MAX_RESULTS}"
      end

      response = RestClient.get(url)
      data = JSON.parse(response.body)

      #iterate over all the books in that response
      books = data['items'].map do |book_data|
        book = Book.find_or_initialize_by(title: book_data['volumeInfo']['title'], description: book_data['volumeInfo']['description'])
        book.pages = book_data['volumeInfo']['pageCount']
        book.image_url = book_data['volumeInfo']['imageLinks']['thumbnail']

        if  book_data['volumeInfo']['authors']
          author_name =  book_data['volumeInfo']['authors'].first
          author = Author.find_or_create_by(name: author_name)
        end

        # create and save the book objects and associated authors
        book.author = author
        book.save
        book
      end
    end

    def seed_db
      start_index = 0

      while start_index < 300
        self.fetch_books(start_index)
        start_index += MAX_RESULTS
      end
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  def self.fuzzy_search(term)
    fuzzy_term = "%#{term}%"
    Book.where('title LIKE ? OR description LIKE ?', fuzzy_term, fuzzy_term)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    if params[:search]
      @books = Book.fuzzy_search(params[:search])
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<div class='ui centered grid'>
  <div class='two wide column'></div>
  <div class='six wide column'>
    <%= form_tag '/books', method: :get, class: 'ui form' do %>
      <div class="field">
        <label>Search Books</label>
        <%= text_field_tag :search, nil, placeholder: 'Enter search term' %>
      </div>
      <%= submit_tag 'Search Books', class: 'ui blue button' %>
    <% end %>
  </div>

  <div class='six wide column'>
    <div class="ui relaxed divided list">

      <% @books.each do |book| %>
        <div class="item">
          <i class="large book middle aligned icon"></i>
          <div class="content">
            <%= link_to book.title, book_path(book), class: 'header' %>
            <div class="description">
              <%= book.author.name %>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>

  <div class='two wide column'></div>

</div>

app/views/books/show.html.erb
<div class='ui two column centered grid'>
  <div class="column">

    <div class="ui fluid card">
      <div class="image">
        <%= image_tag(@book.image_url) %>
      </div>
      <div class="content">
        <h1 class="ui header">
          <%= @book.title %>
          <div class='sub header'>
            by <%= @book.author.name %>
          </div>
        </h1>
        <div class="meta">
          <span><%= @book.pages %> pages</span>
        </div>
        <div class="ui divider"></div>
        <div class="description">
          <%= @book.description %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookSearcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui inverted teal menu">
      <a class='item' href="/books">
        <h2 class="ui header">
          <i class="search icon"></i>
          <div class="content">
            Book Searchr
          </div>
          <div class="sub header">
            The app that searches for books
          </div>
        </h2>
      </a>
    </div>

    <%= yield %>

  </body>
</html>